[package]
name = "railway"
repository = "https://github.com/nebulatgs/cli-rs/"
description = "Develop and deploy code with zero configuration"
license = "MIT"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {git = "https://github.com/clap-rs/clap", features = ["derive", "suggestions"]}